id: P010394
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:47:31.897089
source_metadata:
  id: bdr:W8LS17334
  title: ལེགས་བཤད་གསེར་གྱི་ཕྲེང་བ།
  author: ''
  volumes:
    9993ea0234464fa18d8d5527ef1e0b7e:
      image_group_id: I8LS17339
      title: ''
      volume_number: 1
      total_pages: 876
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
