id: IACBA5FE6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:09:23+00:00'
last_modified: '2022-06-08T13:16:34.726048+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17334
  title: ལེགས་བཤད་གསེར་གྱི་ཕྲེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3439':
      image_group_id: I8LS17339
      title: ''
      total_pages: 876
      order: 1
      base_file: 3439.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
